# Generated by Django 4.1.7 on 2023-03-06 16:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the project", max_length=256
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unique ID for this approval",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title for the request", max_length=256
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter the description of this request",
                        max_length=1024,
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "beneficiary",
                    models.CharField(
                        help_text="Enter the name of the beneficiary", max_length=256
                    ),
                ),
                (
                    "beneficiary_account",
                    models.CharField(
                        help_text="Enter the bank account number of the beneficiary",
                        max_length=256,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("p", "Processing"),
                            ("a", "Approved"),
                            ("d", "Declined"),
                            ("c", "Commented"),
                        ],
                        default="p",
                        help_text="Select the status of the approval",
                        max_length=1,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="approvals.project",
                    ),
                ),
            ],
            options={"ordering": ["created_at"],},
        ),
    ]
